#!/bin/bash

# Generic
alias ls="ls -hN --color=auto --group-directories-first"
alias la="ls -a"
alias ll="ls -al"

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias md="mkdir -pv"
del() { mv "$@" ~/.trash }

alias pacman="sudo pacman"
alias up='sudo pacman -Syu --noconfirm --needed - < "/home/ryan/dotfiles/bootstrap/packages/default.txt" && yay -Syu --noconfirm --needed - < "/home/ryan/dotfiles/bootstrap/packages/aur.txt"'

alias limbo='(){ mv $@ .limbo }'
alias v="nvim"
alias tmux="tmux -u2"

alias howbig="du -sh"

# Git
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gca="git commit --amend --no-edit"
alias gpl="git pull"
alias gp="git push"
alias gpf="git push --force"
alias gq="git commit --amend --no-edit && git push --force"
alias glo="(){ git log --oneline -$([ -z $1 ] && echo 5 || echo $1) }"alias gb="git checkout"
alias gbn="git checkout -b"

# Cloud
alias k=kubectl
