apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: utkuozdemir
  pass_credentials_all: false
  password: ""
  url: https://utkuozdemir.org/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cilium
  pass_credentials_all: false
  password: ""
  url: https://helm.cilium.io/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cloudflare
  pass_credentials_all: false
  password: ""
  url: https://cloudflare.github.io/helm-charts
  username: ""
